### PR TITLE
Create install.py

### PR DESCRIPTION
**Pull request by unaveragetech**
**feat: Improved install script with error handling, installation checks, and self-destruct feature**

**This commit introduces several enhancements to the installation script, including robust error handling, thorough installation checks, and a self-destruct feature that allows for complete uninstallation in reverse order of installation. While some of these features may seem redundant or overly cautious for a basic setup, they reflect a good practice of being explicit about what the script is doing at every step, improving user experience and ensuring transparency.** 

Even though the installation prompts and self-destruct mechanism might appear excessive in this specific use case, where the packages involved are generally stable and widely used, the intention is to give users a higher level of control. This is particularly useful for scenarios where:
- Users want to install only selected dependencies.
- Users prefer being able to verify the success of each installation step individually.
- A clean rollback or uninstallation is needed after a test or failed installation.

By implementing such detailed checks and prompts, we also minimize the risk of errors going unnoticed and provide users with a clearer understanding of what’s happening under the hood, leading to a more reliable and maintainable script overall.

This approach may feel like over-engineering in certain situations, but being upfront about each step of the process fosters trust and helps users anticipate the consequences of their choices, making it a best practice in the development of installation scripts.

Summary of changes:
- Added interactive prompts for full reinstall, giving users the ability to opt-out of specific steps.
- Implemented detailed error handling for each installation and uninstallation command.
- Added a self-destruct feature for complete clean-up of installed dependencies, including a confirmation prompt for safety.
- Included thorough checks for installation status after each dependency is processed, to verify successful installations.
- Improved logging and visual indicators for a more transparent and user-friendly experience.

The script now offers improved error resilience and a better user experience, even though the level of granularity might not always be strictly necessary. It’s part of fostering best practices in automation and installation management, ensuring that nothing happens behind the scenes without the user’s knowledge or approval.

This commit enhances the installation script by adding error handling, user prompts, thorough installation checks, and a self-destruct mechanism. Below are the detailed changes and features added:

1. **Error Handling:**
   - The `execute_command` function is now wrapped in a try-except block to catch and handle `subprocess.CalledProcessError`.
   - If an error occurs during installation or execution, a detailed message is shown to the user for troubleshooting.

2. **Thorough Installation Check:**
   - A new function `is_installed()` checks if each dependency is installed after its installation.
   - The `check_installation()` function provides a thorough report on the status of all dependencies after the installation process.
   - This ensures that users can verify whether each required package has been properly installed.

3. **User Prompts Between Installation Steps:**
   - When the `Full Reinstall` option (3) is chosen, the script now prompts the user before installing each dependency.
   - Users can opt to continue with the installation or skip specific dependencies by pressing 'y' (yes) or 'n' (no).
   - This step-by-step prompt ensures that users are in control of the installation process.

4. **Self-Destruct Feature:**
   - A new option (5) allows users to "self-destruct" the installation, which removes all installed dependencies in reverse order.
   - The self-destruct feature prompts the user for confirmation before proceeding with the uninstallation.
   - This feature ensures a clean removal of all components and dependencies that were installed by the script.

5. **Improved Uninstallation:**
   - The script handles uninstallation of existing libraries with the `uninstall_dependencies()` function, allowing users to remove all or partial libraries based on their choice.

6. **Logging and Progress Indicators:**
   - The loading bar function provides a clear visual representation of progress during each installation or uninstallation step.
   - The script logs detailed messages about each step, including successful installs or errors encountered, improving user transparency.

7. **User-Friendly Installation Directory Prompt:**
   - The script prompts users to choose an installation directory using a graphical interface (Tkinter).
   - If no directory is selected, the script safely cancels the installation process, avoiding any unintended changes.

8. **Additional Options in the Menu:**
   - The script now offers multiple options: - Fresh Install (removes all existing libraries) - Partial Reinstall (removes and installs selected libraries) - Full Reinstall (reinstalls all libraries with user prompts between each step) - Check Installation Status (verifies which dependencies are installed) - Self-Destruct (uninstalls everything in reverse order)
   - These options provide flexibility for various installation scenarios and user preferences.

This improved script provides more control, transparency, and safety for users installing or uninstalling dependencies. It allows thorough checks, handles errors gracefully, and offers an easy way to roll back changes with the self-destruct feature. Also shows plainly what is being installed for transparency

### CODE REVIEW

**Comment by LightYagami28** [comment]
The dev is not active pls i made a new repo in my github profile with update code pls contribute to this

**Comment by unaveragetech** [comment]
@LightYagami28 Can you link your fork here so i can add the proposed changes

**Comment by LightYagami28** [comment]
https://github.com/LightYagami28/Symbiote the link

**Comment by LightYagami28** [comment]
Use a dev branch for pr and made a commit specific

**Review by hasanfirnas — APPROVED** [review]

**Comment by hasanfirnas** [comment]
Thank you, @unaveragetech 
I appreciate the effort you put into making the installation smooth and controlled. Great job, and happy to merge this into the project!

**Pull request merged**
